### PR TITLE
Automatic refunding

### PR DESCRIPTION
**Pull request by gCoreByte**
**THIS REQUIRES ADDITIONAL SCOPES**

1. create an app here
https://dev.twitch.tv/console/apps/create
2. go to https://twitchapps.com/tokengen/, copy the url into the callback into the app dashboard
3. put in client id from the app
4. set scopes to `channel:manage:redemptions channel:moderate channel_editor chat:edit chat:read whispers:edit whispers:read`
(i believe we can remove everything besides `channel:manage:redemptions chat:edit chat:read` )
5. copy oauth token into environment variable with format `oauth:{YOURTOKENHERE}`
6. copy client id into environment variable

rest stays the same.

Functionality comes from the twitchcontroller.js file, where a Twitch class is exported. this class is selfcontained and could technically be made into functions in index.js, however for readability I opted for this solution.

New config file options include `automatic_refunds, custom_reward_name, custom_reward_cost`. `automatic_refunds` is simply the toggle for this feature, making it backwards compatible by default. `custom_reward_name, custom_reward_cost` are necessary to create a new reward for automatic refunds to work. This is because the Twitch API does not allow access to redemptions not made by the same client id, meaning you can programatically only access redemptions of a channel reward which was also made programatically by the same app.

### CODE REVIEW

**Comment by KumoKairo** [comment]
Yeah I remember looking into automatic refunds and it required to do all sorts of stuff with app creation and code-based rewards management (that's exactly why I didn't implement it in the first place).

I have checked the code and everything looks nice at a glance. However, I don't see any way to delete the created reward if a person decides to temporarily or completely disable it. If I remember correctly, it is not possible to access app-generated rewards from the Twitch dashboard, so the app needs to manage it completely (i.e. provide a way to delete or pause the reward).

Any thoughts on that?

**Comment by gCoreByte** [comment]
It is possible to remove, edit and disable the reward from the Twitch dashboard as the broadcaster.

**Comment by KumoKairo** [comment]
Can you paste a screenshot of how it looks like in the dashboard please?

**Comment by gCoreByte** [comment]
[Editing the reward](https://cdn.discordapp.com/attachments/708100406022242344/970317226450231296/Screenshot_3.png)
[Editing the reward 2](https://cdn.discordapp.com/attachments/708100406022242344/970317226743836713/Screenshot_4.png)
[Dashboard, app-added reward is 4th from the bottom](https://cdn.discordapp.com/attachments/708100406022242344/970317227230392340/Screenshot_5.png)

**Pull request merged**
