### PR TITLE
Added $(username) parameter functionality for successful song additions.

### PR DESCRIPTION
**Pull request by ghlegend195**
Fixed issue 4 with username not being pulled for message use.

### CODE REVIEW

**Review by ghlegend195 — COMMENTED** [review]
Hey, hold off on this pull: I don't know how to revert it, but something's wrong, and now it won't send any chat messages when a successful request is made

**Comment by ghlegend195** [comment]
it was working before you added the skip function, so i'm looking to see if it's something with that

**Comment by ghlegend195** [comment]
The command still works, still adds the song to the queue, but the message in chat doesn't come up. Additionally, the console readout is printing the "ERROR WHILE REACHING SPOTIFY" part of the try-catch. 

Side note: node is no longer part of the .zip download. Can't find it anywhere on this page now, so a new pull will not run unless the user has node downloaded locally. I had to pull the files from 0.4.0 which i had downloaded on my computer.

**Comment by KumoKairo** [comment]
> Side note: node is no longer part of the .zip download. Can't find it anywhere on this page now, so a new pull will not run unless the user has node downloaded locally. I had to pull the files from 0.4.0 which i had downloaded on my computer.

Yeah it's not on the repository because node is a separate download. It's still packaged in the release, I have just double-checked the 0.5.0 zip archive.

I will add build instructions for people who are willing to develop this on their own. It's just something that I have not anticipated (other people being interested in building the zip release)

**Pull request closed without merging**
